
services:
#Contenidor per Gitea
#Gitea és un gestor de repositoris Git autohostejat
  server:
    image: docker.gitea.com/gitea:latest-rootless
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db_gitea_mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./gitea/data:/var/lib/gitea
      - ./gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db_gitea_mysql
    networks:
      - gitea
#Contenidor per la base de dades de Gitea
#Gitea utilitza una base de dades MySQL
  db_gitea_mysql:
    image: docker.io/library/mysql:8
    restart: always
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
        - db_mysql:/var/lib/mysql
    networks:
      - gitea
#Contenidor per la base de dades de MariaDB
#Aquest contenidor tindrà la base de dades de les aplicacions desenvolupades
  db_mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_USER=user 
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=prova 
      - MARIADB_ROOT_PASSWORD=rootpass
    volumes:
      - db_mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db_mariadb
      - PMA_PORT=3306
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "9090:80"
    depends_on:
      - db_mariadb
#Contenidor per l'aplicació web 
  web:
    image: nginx:latest
    restart: always
    volumes:
    - ./nginx/templates:/etc/nginx/templates
    - ./nginx/data/conf.d:/etc/nginx/conf.d
    - ./nginx/data/certbot/conf:/etc/letsencrypt
    - ./nginx/data/certbot/www:/var/www/certbot
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80
    networks:
      - gitea
volumes:
  db_mysql:
    driver: local
  db_mariadb:
    driver: local
networks:
  gitea:
    driver: bridge

